export const loanDetails = {
  "interest_details": {
    "upfront_interest_period_unit_value": null,
    "upfront_interest_applicable": "true",
    "upfront_interest_period": "1",
    "interest_setup_id": "138",
    "interest_round_off_type": "RND_OFF_TYP_RDN",
    "interest_rounding_factor": "0",
    "upfront_interest_amount": 16199.00,
    "interest_setup_code": "IS_RoundDown",
    "effective_interest_rate": 16.200000,
    "interest_setup_name": "RoundDown Interest setup",
    "interest_calculation_days_in_month": "DIM_ACTUAL",
    "interest_calculation_days_in_month_value": "Actual",
    "account_spread": 4.200000,
    "interest_calculation_days_in_year": "DIY_ACTUAL",
    "scheme_interest_rate": 12.000000,
    "interest_round_off_type_value": "Round Down",
    "upfront_interest_period_unit": null,
    "interest_calculation_days_in_year_value": "Actual"
  },
  "disbursement_details": {
    "mode": "CASH",
    "mode_value": "Cash",
    "expected_disbursement_date": "1632421800000",
    "disbursement_amount": 83801.00
  },
  "repayment_details": {
    "installment_multiples_of_value": "0",
    "interest_calculation_basis_value": "Reducing Balance",
    "number_of_installments": "1",
    "interest_frequency_value": null,
    "interest_calculation_basis": "REDUCING_BALANCE",
    "maturity_date": "1663957800000",
    "installment_type": "INSTL_TYP_BULT",
    "first_interest_payment_date": 1663957800000,
    "mode": "CASH",
    "mode_value": "Cash",
    "installment_rounding_type_value": null,
    "installment_rounding_type": null,
    "interest_frequency": null,
    "repayment_frequency": "MONTHLY",
    "repayment_frequency_value": "Monthly",
    "installment_rounding_factor": "0",
    "first_repayment_date": "1663957800000",
    "installment_multiples_of": "ZERO",
    "installment_type_value": "Bullet Payment",
    "principal_rounding_factor": "0"
  },
  "disbursement_repayment_account_details": [],
  "loan_details": {
    "product_scheme_id": "306",
    "account_number": "0000000646",
    "product_scheme_name": "uibullet",
    "loan_category": "LOAN_PERS",
    "office_code": "IDFCP1",
    "loan_status_value": "Active",
    "loan_category_value": "Personal Loan",
    "loan_product_id": "321",
    "product_code": "UIBulletUP",
    "loan_purpose": null,
    "currency_code": "INR",
    "loan_product_version": "0001",
    "office_id": "1",
    "product_id": "340",
    "loan_term_unit_value": "Months",
    "id": "651",
    "customer_code": "0000000409",
    "loan_status": "ACTIVE",
    "currency_code_value": "INR",
    "loan_amount": 100000.00,
    "product_name": "UIBulletUP",
    "loan_term_unit": "MONTH",
    "submitted_on_date": "1632421800000",
    "office_name": "IDFC Head Office",
    "customer_photo": null,
    "loan_term": "12",
    "loan_purpose_value": null,
    "customer_name": "Test Type Individual",
    "product_scheme_code": "uibullet",
    "customer_id": "123"
  }
}
